### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by Nonlimit** [silvestreh/atom-material-syntax#1]
Default Atom have Suntax Them - One Dark, when you click on tag he have backlight and solid underline like on screenshot, please create this on your Material Syntax.
![tag](https://cloud.githubusercontent.com/assets/11960153/8396599/d2832cbe-1db5-11e5-9c28-f4a7045780af.PNG)

**Comment by silvestreh** [comment]
Done! Check for updates.

**Comment by Nonlimit** [comment]
Thank)
