### ISSUE TITLE
Dark Version 

### ISSUE THREAD

**Issue by MohhamedRafi** [silvestreh/atom-material-syntax#16]
Is there any plan on creating a dark version of this theme (sublime text port maybe +1)

**Comment by silvestreh** [comment]
Sure, I don't see why not. It would be in a different repository though.

**Comment by MohhamedRafi** [comment]
I don`t know if I should put this here but do you know how to change the scale of editor. Everything look to zoomed in. If you know to how to fix this or add a fix to the dark version it would be +1

**Comment by MrAndrewSaint** [comment]
+1
I find that the dark version is more aesthetically pleasing.

**Comment by equinusocio** [comment]
:+1:

**Comment by silvestreh** [comment]
Yes, I will convert @equinusocio's dark syntax theme. I'm rewriting the UI theme right now, getting rid of all the inherited baggage from Atom Dark (the theme I forked.) It'll take some time :smile:

**Comment by MohhamedRafi** [comment]
I thought you guys forked @equinusocio theme originally.

**Comment by silvestreh** [comment]
@MohhamedRafi not exactly, no. Both themes share the same visual language and the Atom theme is based off of @equinusocio's vision for a MD text editor, but they don't share a single line of code so. technically speaking, it's not a fork.

**Comment by equinusocio** [comment]
...and because Atom and Sublime Text are text editors developed on two different languages. :+1:

**Comment by silvestreh** [comment]
[Done!](https://github.com/silvestreh/atom-material-syntax-dark)

**Comment by MrASaint** [comment]
Awesome Christmas present, thank you :)

**Comment by equinusocio** [comment]
:+1:

**Comment by equinusocio** [comment]
This is a good UX with atom. ;)
![screen shot 2015-12-24 at 21 14 25](https://cloud.githubusercontent.com/assets/10454741/11997713/5969689c-aa83-11e5-833d-98350c5b0906.png)

**Comment by MohhamedRafi** [comment]
This look nice! :)
