### ISSUE TITLE
sidebar opened projects  

### ISSUE THREAD

**Issue by Mocha--** [silvestreh/atom-material-syntax#19]
When I add a new project folder, the previous ones go invisible. When I remove the current project folder, the previous one goes visible, which is like pushing those folders into a stack. However, I think this really upsets me because it costs me a lot of time to switch between projects(I have to add and remove ......).

**Comment by silvestreh** [comment]
I see… I'll push a fix ASAP. Thanks!

**Comment by Mocha--** [comment]
At the very beginning, I thought it was my config issue. lol.

Material is my best theme for ATOM and Sublime.

Thanks,

Silvestre Herrera <notifications@github.com>于2015年12月1日周二 下午1:54写道：

**Comment by silvestreh** [comment]
@Mocha-- this was an issue with the UI theme (with the 1.0 release in particular). 1.0 was unpublished, you should either downgrade to 0.8.0 (just by reinstalling the theme) or you're welcome to test the development version in the repository.

**Comment by silvestreh** [comment]
This has been fixed in the development version. You can find instructions on how to install it in the [https://github.com/silvestreh/atom-material-ui/blob/master/README.md#contributing](contributing section of the readme file).
