### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by stretchtiberius** [silvestreh/atom-material-syntax#20]
The changelog.md only has notes for version 0.1.0

**Comment by silvestreh** [comment]
Yeah, that one was generated by `APM`. I never tracked changes in there. I might as well delete it, unless there's an automatic way of adding stuff from commit messages.

I can see how changelogs are useful, I just suck at keeping them updated.

**Comment by stretchtiberius** [comment]
Deleting it may be better than having it be out of date. That way it does not show up as a link within atom.

**Comment by silvestreh** [comment]
Will do. Thanks for pointing this up :smile:
