### ISSUE TITLE
CoffeeScript & SCSS highlights looks weird.

### ISSUE THREAD

**Issue by AlexanderKozhevin** [silvestreh/atom-material-syntax#21]
![screen shot 2016-01-04 at 22 57 19](https://cloud.githubusercontent.com/assets/4464561/12099013/cb9aa3b6-b336-11e5-882c-03b1c6bd0473.png)
![screen shot 2016-01-04 at 22 57 59](https://cloud.githubusercontent.com/assets/4464561/12099014/cbcbdfbc-b336-11e5-99da-5c4048762c25.png)

**Comment by silvestreh** [comment]
What's weird about these? Please elaborate or I'll have to close the issue.
