### ISSUE TITLE
attr class and other

### ISSUE THREAD

**Issue by Nonlimit** [silvestreh/atom-material-syntax#22]
![capture](https://cloud.githubusercontent.com/assets/11960153/12299448/778b661c-ba1f-11e5-8710-6da7cad87fe3.PNG)
Please change color class and other.You have the same color, and because of this all spreads.
Example Syntax Atom One Dark
![capture](https://cloud.githubusercontent.com/assets/11960153/12299585/f1b8d88e-ba1f-11e5-9c59-f3ee957aeda9.PNG)
I think this is looks better

**Comment by equinusocio** [comment]
Provide more details or i will close the issue. Thanks

**Comment by silvestreh** [comment]
@equinusocio I believe he means that HTML attributes and their associated values have the same color. Probably something APM missed while converting your theme.

**Comment by equinusocio** [comment]
You have this issue?

**Comment by silvestreh** [comment]
yep, while using the default syntax variant (that means, not the light or dark one)…
