### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ddagone** [silvestreh/atom-material-syntax#23]
I can't find it on the Atom software package search tool, 
And how am I supposed to install it ?

**Comment by silvestreh** [comment]
It's there.
![captura de pantalla 2016-01-23 a las 13 36 26](https://cloud.githubusercontent.com/assets/1133339/12531331/7a4eff08-c1d6-11e5-914b-46b3b9b9a501.png)

Alternatively, you can use your command line to install it: `apm install atom-material-syntax`

**Comment by ddagone** [comment]
i'm sorry but I can't handle it, I installed it via the command line, but
It doesn't show up in atom, when you choose a  syntax theme
I have the atom-material theme installed too maybe it's the reason why it
doesn't show up ?
Best regards

2016-01-23 17:38 GMT+01:00 Silvestre Herrera <notifications@github.com>:

**Comment by silvestreh** [comment]
Did you restart Atom after installing from the command line? If so, then you might have an issue with your Atom install.

**Comment by ddagone** [comment]
Yes! I did, but still nothing, I'll keep trying
yeah, It's probably my fault, but good job, are you designer ?

Le samedi 23 janvier 2016, Silvestre Herrera <notifications@github.com> a
écrit :
