### ISSUE TITLE
New releases make One Dark UI ugly

### ISSUE THREAD

**Issue by eramdam** [silvestreh/atom-material-syntax#25]
The Settings' UI have become unreadable with the last releases of the dark and regular syntax.

![screen shot 2016-01-28 at 1 29 14 pm](https://cloud.githubusercontent.com/assets/1409924/12659342/2b8f74b0-c5c3-11e5-9aae-b228d604dcfe.png)
![screen shot 2016-01-28 at 1 29 17 pm](https://cloud.githubusercontent.com/assets/1409924/12659343/2b96dbb0-c5c3-11e5-86f0-d84dc83f0f41.png)

**Comment by eramdam** [comment]
The issue is also visible with Nucleus Dark which is also adapting depending on the syntax theme

**Comment by silvestreh** [comment]
Just reverted the latest changes. They were meant to be used with Material UI, but apparently were not specific enough to avoid breaking other stuff.
