### ISSUE TITLE
Selecting text causes line highlight to disappear

### ISSUE THREAD

**Issue by WoodyWoodsta** [silvestreh/atom-material-syntax#26]
Not entirely sure if this is intended or not, but when you select the text, the current line highlight disappears. Seems a little strange to me.

No text selected:
![withoutselection](https://cloud.githubusercontent.com/assets/8268040/12694125/ec95ca2a-c72a-11e5-9093-af62b11567bc.png)

Text selected:
![withselection](https://cloud.githubusercontent.com/assets/8268040/12694126/eeee05ee-c72a-11e5-8eaa-0bd4be5176a4.png)

**Comment by silvestreh** [comment]
Yes, this is expected behavior. It's how Atom works.

**Comment by WoodyWoodsta** [comment]
Sorry about that. I probably should have checked a different syntax theme before posting!

**Comment by silvestreh** [comment]
It's ok. Issues are always welcome 😉
