### ISSUE TITLE
JavaScript variables and brackets are colored incorrectly

### ISSUE THREAD

**Issue by D1SC0tech** [silvestreh/atom-material-syntax#27]
Here's what a block of JavaScript looks like with atom-material-syntax (dark):

![screen shot 2016-01-31 at 02 11 05](https://cloud.githubusercontent.com/assets/3586264/12701058/940a5aa0-c7c1-11e5-9a0d-a15236573656.png)

And here's what the same code looks like with One Dark syntax:

![screen shot 2016-01-31 at 02 11 21](https://cloud.githubusercontent.com/assets/3586264/12701060/a86a65da-c7c1-11e5-92e9-079bac5f9dff.png)

The problems begin at the first line. The left parenthesis, comma, and bracket are all highlighted in the 'function' color when they should be plain instead. This carries over to line 2 where both the variable name and the semicolon are highlighted. Strangely enough, the 'element' variable is highlighted correctly later on in the same file.

I'm pretty sure it's been this way ever since I first installed it a month or so ago, so it most likely isn't a recent regression. Let me know if you need any more info. Thanks!

**Comment by chifreaigle** [comment]
Yeah i noticed that, "(" should be in an other color
