### ISSUE TITLE
Multiple parameter functions are miscolored

### ISSUE THREAD

**Issue by krrg** [silvestreh/atom-material-syntax#3]
In version 0.1.2, parameters were uniformly colored, for instance:
<img width="536" alt="screen shot 2015-07-08 at 9 56 56 pm" src="https://cloud.githubusercontent.com/assets/8496492/8587685/8bc3de18-25bc-11e5-8698-329d91747930.png">

In version 0.2.0, the first parameter is colored, but the rest are still white:
<img width="536" alt="screen shot 2015-07-08 at 9 57 52 pm" src="https://cloud.githubusercontent.com/assets/8496492/8587686/8f0552be-25bc-11e5-901d-dcb3d8945ebb.png">

I have temporarily downgraded to 0.1.2, which has the correct coloring for parameters.

P.S. --> this is an awesome theme!

**Comment by alexbeletsky** [comment]
Having the same problem. Looks quite annoying, would be great to fix it. 

@krrg can you please explain how you downgraded to the previous version?

**Comment by silvestreh** [comment]
Should be fixed now! Sorry about that.

**Comment by krrg** [comment]
Looks good, thanks @silvestreh 

@alexbeletsky  --- to downgrade to a specific version, I used the `apm` command line tool (it should be installed as part of atom).

    apm remove atom-material-syntax
    apm install atom-material-syntax@0.1.2

The latest update fixes the issue, so you (hopefully) won't need to downgrade.
