### ISSUE TITLE
Python Method Highlighting

### ISSUE THREAD

**Issue by ryanjcain** [silvestreh/atom-material-syntax#30]
Hey Man!

Keep up the great work! This is by far the best syntax theme on atom!  I recently updated to the newest version of this theme and it does not highlight .methods() in python like it used to.  It makes parts of my code hard to read and was wondering if there is any way you could bring this back!  Thank you!

-Ryan

**Comment by simon-lifelike** [comment]
Same issue in php. Seems like `function-call` doesn't have any styling at all.

**Comment by simon-lifelike** [comment]
Seems like was removed in #28. Surely there must be a way to implement a better fix rather than removing the styling for all function calls?

**Comment by silvestreh** [comment]
Would you be kind enough to check if the latest update fixed your issue. I just synced the styles with the latest version from Sublime's version. This syntax theme is actually a simple port from the Sublime's version.

**Comment by simon-lifelike** [comment]
Ah, I see. Seems like that fixed it :)

Thanks!

JS
![screenshot from 2016-02-18 17-07-49](https://cloud.githubusercontent.com/assets/5887301/13149586/438a9e64-d662-11e5-82a1-0b417a4bebc1.png)

PHP
![screenshot from 2016-02-18 17-08-17](https://cloud.githubusercontent.com/assets/5887301/13149589/470922cc-d662-11e5-94be-9776e440fe93.png)

Python
![screenshot from 2016-02-18 17-04-48](https://cloud.githubusercontent.com/assets/5887301/13149526/0d8e0454-d662-11e5-8025-41240f45702e.png)

**Comment by ryanjcain** [comment]
Totally Works!  Thank you so much for working on this!

-Ryan

On Thu, Feb 18, 2016 at 7:55 AM, Silvestre Herrera <notifications@github.com

**Comment by D1SC0tech** [comment]
Sorry about the accidental regression in my PR. Unfortunately, the problem of parens and semicolons being colored (#27) still remains, I'm trying to come up with a better fix now.

**Comment by ryanjcain** [comment]
No worries, I hope you will be able to iron it out.  I noticed another
small change in the most recent update as well.  Not as large of an issue,
but "self" used to have syntax highlighting when working with classes
previously. I am not sure if the change was intentional or not, but at the
end of the day I still love the style.  Thanks for all your hard work and
the regular improvements.  Keep it up!

Regards,
Ryan

**Comment by D1SC0tech** [comment]
I'm working on a separate [material dark syntax](https://github.com/D1SC0tech/material-dark-syntax) theme, mainly just for fun. Currently there's only a dark variant. Let me know what you think over on the repo, I'd love to hear any suggestions/fixes!

@silvestreh I'll get out of your hair here, I don't want to clutter this issue up. And thanks again for the fantastic UI/syntax themes, I use them every day!

**Comment by hrvoojex** [comment]
Could it be possible to highlight only method call like here? Only the method, not the object name.

![screenshot_20170623_134641](https://user-images.githubusercontent.com/11456950/27481832-06f1c258-581f-11e7-99d9-8129cf336507.png)

**Comment by zerzhul** [comment]
@hrvoojex  I found that using this syntax theme along with MagicPython syntax highlighter did what you suggested, which is what I was looking for when I found this syntax theme to start with.
