### ISSUE TITLE
new version break JS color

### ISSUE THREAD

**Issue by DouglasHennrich** [silvestreh/atom-material-syntax#31]
Just update to the newest version and it break's javascript's color files

**Comment by silvestreh** [comment]
Breaks in what way? I actually just sync'd the theme with Sublime's version… which basically is all that I do for this theme…

Share screenshots and better describe your problem. I can't do anything with "breaks javascript's color files". :smile:

**Comment by DouglasHennrich** [comment]
hahaha sure, my bad

new version:
![captura de tela 2016-02-18 as 15 02 15](https://cloud.githubusercontent.com/assets/10107024/13151365/f4599860-d650-11e5-960a-b756e486f852.png)

previous version:
![captura de tela 2016-02-18 as 14 13 09](https://cloud.githubusercontent.com/assets/10107024/13151371/fbd0bbaa-d650-11e5-9a9b-255fba1c2acf.png)

**Comment by silvestreh** [comment]
I don't see it as broken. It's just slightly different. Besides, the latest update fixed #30 where methods were not being properly highlighted.
