### ISSUE TITLE
JSON stopped highlighting after first level of keys in 0.4.0

### ISSUE THREAD

**Issue by bradynpoulsen** [silvestreh/atom-material-syntax#32]
I just ran the update for version 0.4.0 and JSON syntax doesn't highlight after the keys of the first layer

![screen shot 2016-02-18 at 11 54 28 am](https://cloud.githubusercontent.com/assets/5748275/13154543/ac704f04-d636-11e5-9862-4758f167438a.png)

**Comment by silvestreh** [comment]
Yeah, I noticed this too… I reconverted the sublime text theme for 0.4.0 (which is what I usually do) and a couple things got a little messed up… this is one of them. I'm working through today's issues expect a patch soon :smile:

**Comment by bennyp123** [comment]
JSON arrays don't highlight properly
https://infinit.io/_/qYaGhNs
