### ISSUE TITLE
No highlighting for instance variables in Ruby

### ISSUE THREAD

**Issue by hnguyen94** [silvestreh/atom-material-syntax#33]

**Comment by silvestreh** [comment]
I know jack about Ruby… would you care to share a screenshot and a snippet of code so I can test this out?

**Comment by hnguyen94** [comment]
Sure. I downgraded to 0.3.3. In Version 0.4.0 @orders is white.. 

![screen shot 2016-02-18 at 23 20 31](https://cloud.githubusercontent.com/assets/8395044/13160182/41e9849c-d696-11e5-8be5-0286d0ed07a7.jpg)

**Comment by silvestreh** [comment]
should be golden now!
