### ISSUE TITLE
Code highlighting

### ISSUE THREAD

**Issue by hubertprein** [silvestreh/atom-material-syntax#34]
I love the theme and color scheme, however highlighting some text, is really hard to see what you have highlighted.

Atom: http://cl.ly/281W3u3N2d24
Sublime: http://cl.ly/3x2X0D2e0W2z

Any chance you might update this like the sublime variant?

**Comment by haveanicedavid** [comment]
@hubertprein I have the same complaint, but worked around it by modifying my own atom stylesheet: 
```
atom-text-editor::shadow {
  .selection .region {
    background-color: rgba(35, 96, 162, 0.43);
  }
}
```
