### ISSUE TITLE
parameter in javascript function

### ISSUE THREAD

**Issue by seanmars** [silvestreh/atom-material-syntax#35]
The color of parameter  in javascript function is same to function;

**Comment by silvestreh** [comment]
Sorry for the huge delay. This might've been fixed in a previous release so I'll close the issue.

![captura de pantalla 2016-03-24 a las 15 28 56](https://cloud.githubusercontent.com/assets/1133339/14027192/2c3c1aa6-f1d5-11e5-9f78-1cf7b5aa5829.png)

**Comment by seanmars** [comment]
Thanks a lot.
