### ISSUE TITLE
PHP coloring on closing tags

### ISSUE THREAD

**Issue by britnidesigns** [silvestreh/atom-material-syntax#36]
Previously the PHP opening and closing tags were completely red, but since recent updates, the closing tag is not consistent. The `?` is white, while the `>` is red.

![image](https://cloud.githubusercontent.com/assets/6564393/13968299/424809c4-f039-11e5-8b87-758d021ebe49.png)

Even though this is a minor issue, i've noticed it does reduce the inline readability quite a bit.

_Version 0.4.3_

**Comment by silvestreh** [comment]
Yep, I noticed this too. Totally forgot to fix it though…
