### ISSUE TITLE
JSON Arrays not highlighted properly

### ISSUE THREAD

**Issue by bennyp123** [silvestreh/atom-material-syntax#38]
no key:value differentiation in JSON arrays:

<img width="628" alt="screen shot 2016-04-04 at 7 44 18 pm" src="https://cloud.githubusercontent.com/assets/1466420/14255655/b70ec374-fa9d-11e5-8e6b-b280d707c8d6.png">

**Comment by bradynpoulsen** [comment]
Which version are you using?

**Comment by bradynpoulsen** [comment]
@silvestreh I can confirm this happens in 0.4.5 when an object is nested inside of an array. Objects still highlight properly on their own

**Comment by silvestreh** [comment]
Done! I published an updated theme :smile:

Thanks for pointing it out
