### ISSUE TITLE
Problem with colors in JS

### ISSUE THREAD

**Issue by azastrael** [silvestreh/atom-material-syntax#39]
Hey !

Is it normal that :

![2ff7e544-9415-11e5-8c82-4ba4609eeb7e](https://cloud.githubusercontent.com/assets/8067794/14411755/996571f2-ff51-11e5-863d-6e9ad6afd787.png)

became that  :

![](http://i.imgur.com/88xuS8s.png)

( I mean for the syntax of course )

**Comment by silvestreh** [comment]
It's hard to tell what the problem is because both snippets are radically different.

**Comment by azastrael** [comment]
Hey !

Yeah sorry so here are the problems that I can see :
- The brackets are in blue
- `module` isn't in red

**Comment by willviles** [comment]
**v0.3.3**
<img width="571" alt="screen shot 2016-04-21 at 19 43 29" src="https://cloud.githubusercontent.com/assets/2046935/14720482/91145256-07f9-11e6-9676-fcda6c335bf2.png">

**v0.4.0 >=**
<img width="585" alt="screen shot 2016-04-21 at 19 44 03" src="https://cloud.githubusercontent.com/assets/2046935/14720500/a9ee51a0-07f9-11e6-9532-5d07d4244106.png">

I've downgraded to version 0.3.3: 
`apm install atom-material-syntax@0.3.3`

**Comment by silvestreh** [comment]
Sorry for the delay… yes, it was an intended change as it matches the ported textmate theme.
