### ISSUE TITLE
Background color of ui is altered with this syntax theme applied

### ISSUE THREAD

**Issue by Nxt3** [silvestreh/atom-material-syntax#5]
[This is what Atom looks like if I apply both this syntax and your ui-them](http://i.imgur.com/vkm6gD6.png).

I don't think this is correct, considering your screenshot shows it up having a gray background. Not sure what's going on.

**Comment by silvestreh** [comment]
That looks right. I probably had the `contrasting panels` option enabled when I took the screenshot.

**Comment by Nxt3** [comment]
Ah, gotcha. Thank you!
