### ISSUE TITLE
Images not available while using atom-material-ui and atom-material-syntax themes

### ISSUE THREAD

**Issue by arunkpatra** [silvestreh/atom-material-syntax#7]
Images not available while using atom-material-ui and atom-material-syntax themes.
![images-not-available](https://cloud.githubusercontent.com/assets/2806069/9107283/b2c5111a-3c43-11e5-8941-ae35b9a6e98d.png)

**Comment by silvestreh** [comment]
Not related to the syntax theme. Also, the UI theme only modifies the styles, not DOM elements. I've had this happen to me a few times and attributed it to network issues.

**Comment by gdborton** [comment]
@silvestreh I think this is related to the image paths.  Looks like relative paths don't work on atom.io... probably not in the editor either.

https://atom.io/themes/monokai  <-- working
https://atom.io/themes/atom-material-syntax <-- not working

**Comment by silvestreh** [comment]
Yeah, I noticed that. That happens when referencing an image from within the repository. I think it's extremely low priority, that's why it's still broken.

**Comment by silvestreh** [comment]
@arunkpatra @gdborton Looks like Atom caches those images and then fails to load them from the cache. This, I believe, is not a problem with the syntax theme.
