### ISSUE TITLE
atom-material-syntax-dark variation

### ISSUE THREAD

**Issue by theproducer** [silvestreh/atom-material-syntax#9]
There is also a dark variation of the original Sublime theme that would be nice to have:
![](https://camo.githubusercontent.com/3e08a97d754fc56dc8ea55cab6047e250ad29d38/687474703a2f2f657175696e75736f63696f2e6769746875622e696f2f6d6174657269616c2d7468656d652f6173736574732f696d672f6461726b6572312e706e67)

**Comment by silvestreh** [comment]
This would require an entire new Atom package. I'll probably resolve this in the UI package with a setting for a darker background.

I'll close this issue as it doesn't have a place in this repository, but I'll add the feature, don't worry!

**Comment by theproducer** [comment]
Cool, looking forward to it!
